name: Unit tests

on:
  push:
    branches:
      - test-integration

jobs:

  compile-tests:
    name: Compile Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Compile catch2
      run: g++ -Wall test/unitTests/unitTestsMain.cpp test/unitTests/exampleCheckNumbers.cpp -o test/compiledTests
    - name: test 2
      run: ./test/compiledTests
  
  second-job:
    name: Second Job
    runs-on: ubuntu-latest
    needs: compile-tests